Allow export of raw anonymize data
fedor57/alumni-57-poll pull request #1
Opened 2017-05-02 16:46 UTC by vkryukov

Suggestion for creating an anonymized raw data export, consisting of timestamps, hash of codes, and actual votes.

2017-05-02 16:55 UTC, vadz requested changes
You need to deal with people who voted without codes, i.e. compute the hash from the class-name-surname if the code is empty too.

2017-05-02 16:55 UTC, vadz commented on elections57_results.py
> +            writer.writerow([row[col_timestamp], hash(row[col_code]), row[col_candidates]])
I think you need `.encode(utf-8)` for the last argument here.

2017-05-02 16:55 UTC, vadz commented on elections57_results.py
> +    SALT = input("Enter salt: ") # Or any other method to get SALT known to organizers
I'd take it on command line, as an option -- script runs should be reproducible,

2017-05-02 16:55 UTC, vadz commented on elections57_results.py
> +        return hashlib.sha256(code + SALT).hexdigest()
I _think_ this is secure enough, but I'm _not_ 100% sure that this is safe if somebody really bothers to precompute a "rainbow table" with enough hashes and all voters names (see below). I'd use bcrypt just to be totally safe.

2017-05-09 17:39 UTC, vkryukov commented
Closing this to make the new code based on Vadim's other suggestion

2017-05-09 17:39 UTC, closed without merging